-- Neovim colors generated by wallust
local colors = {
  background = "{{background}}",
  foreground = "{{foreground}}",
  cursor     = "{{cursor}}",
  color0     = "{{color0}}",
  color1     = "{{color1}}",
  color2     = "{{color2}}",
  color3     = "{{color3}}",
  color4     = "{{color4}}",
  color5     = "{{color5}}",
  color6     = "{{color6}}",
  color7     = "{{color7}}",
  color8     = "{{color8}}",
  color9     = "{{color9}}",
  color10    = "{{color10}}",
  color11    = "{{color11}}",
  color12    = "{{color12}}",
  color13    = "{{color13}}",
  color14    = "{{color14}}",
  color15    = "{{color15}}",
}

if vim.g.colors_name then
  vim.cmd("hi clear")
end
vim.o.termguicolors = true
vim.g.colors_name = "wallust"

local set_hl = vim.api.nvim_set_hl

-- Base editor highlights
set_hl(0, "Normal", { fg = colors.foreground, bg = colors.background })
set_hl(0, "NormalFloat", { fg = colors.foreground, bg = colors.color0 })
set_hl(0, "FloatBorder", { fg = colors.color4, bg = colors.color0 })
set_hl(0, "Cursor", { fg = colors.background, bg = colors.cursor })
set_hl(0, "CursorLine", { bg = colors.color0 })
set_hl(0, "LineNr", { fg = colors.color7 }) -- Uses color7 instead of dark color8
set_hl(0, "CursorLineNr", { fg = colors.color4, bold = true })
set_hl(0, "SignColumn", { fg = colors.color7, bg = colors.background })
set_hl(0, "StatusLine", { fg = colors.foreground, bg = colors.color0 })
set_hl(0, "StatusLineNC", { fg = colors.color7, bg = colors.background })
set_hl(0, "Visual", { bg = colors.color0 })

-- Syntax highlights
set_hl(0, "Comment", { fg = colors.color7, italic = true }) -- Uses bright color7
set_hl(0, "Constant", { fg = colors.color14 })
set_hl(0, "String", { fg = colors.color12 })
set_hl(0, "Identifier", { fg = colors.foreground })
set_hl(0, "Function", { fg = colors.color4 })
set_hl(0, "Statement", { fg = colors.color4, bold = true }) -- Swapped color5 for color4
set_hl(0, "Keyword", { fg = colors.color6, bold = true })   -- Swapped color5 for color6
set_hl(0, "Operator", { fg = colors.color6 })
set_hl(0, "PreProc", { fg = colors.color6 })

-- Treesitter syntax support (Fixes bash keywords like 'export' & 'alias')
set_hl(0, "@keyword", { fg = colors.color6, bold = true })
set_hl(0, "@keyword.directive", { fg = colors.color4, bold = true })
set_hl(0, "@comment", { fg = colors.color7, italic = true })
set_hl(0, "@variable", { fg = colors.foreground })
set_hl(0, "@string", { fg = colors.color12 })

-- Diagnostics (Fixed typo: colors.fo -> colors.color1)
set_hl(0, "DiagnosticError", { fg = colors.color1 })
set_hl(0, "DiagnosticWarn", { fg = colors.color14 })
set_hl(0, "DiagnosticInfo", { fg = colors.color4 })
set_hl(0, "DiagnosticHint", { fg = colors.color6 })

return colors