font_family      CaskaydiaCove Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14.0

cursor_shape block
cursor_beam_thickness 1.5

confirm_os_window_close 0

tab_bar_edge bottom
tab_bar_margin_width 0.0
tab_bar_margin_height 0.0 0.0
tab_bar_style slant
tab_bar_align left

background_opacity 0.8
background_blur 1

cursor_trail 3

# Vertical split (side by side)
map ctrl+shift+enter launch --location=vsplit

# Horizontal split (top & bottom)
map ctrl+shift+alt+enter launch --location=hsplit

# Move between panes
map ctrl+shift+left  neighboring_window left
map ctrl+shift+right neighboring_window right
map ctrl+shift+up    neighboring_window up
map ctrl+shift+down  neighboring_window down

include ./colors.conf
